.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH METAMORPHOSE2 1 "2010-12-05"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\"
.\" Process this file with
.\" groff -man -Tlatin1 metamorphose2.1

.SH NAME
Métamorphose2 \- a graphical mass renaming tool for files and folders.

.SH SYNOPSIS
.B metamorphose2
[/path/to/open/spaces ok]
.br
.B metamorphose2
[-t] [-d] [-p /path/to/open] [[-c /path/to/file.cfg] [-a level (0-3)]] [-l language]

.SH DESCRIPTION
A GUI renaming tool with many powerful functions. Well suited for those
that need to rename many files and/or folders on a regular basis. In addition to
general usage operations, it is useful for photo and music collections,
webmasters, programmers, legal and clerical, et cetera.

There is support for automating GUI tasks via command line, using the options
described below.

.SH OPTIONS
.B There are two modes for options.

In the first mode, the only available option is a path to open. It is simply passed
as the only argument to the command, spaces may be used.
This mode cannot be used with any other options.

In the second mode, all options can be used but the option type must be declared.
This is similar to almost all Unix type commands.
A path to open would be specified using '-p', and spaces must be escaped.

Modes are switched automatically, based on the structure of the options.

.B Available Options :
.TP
-h,  --help       Show help screen and exit.
.TP
-t,  --timer      Show time taken to complete operations.
.TP
-d,  --debug      Show debugging information.
.TP
-p, --path        Specify a directory to load.
.TP
-c, --config      Specify a configuration file to load.
.TP
-a, --auto        Specify automatic mode level to use with configuration file :
                    0 = do not preview items
                    1 = auto preview items
                    2 = auto rename items
                    3 = auto rename items and exit on success
.TP
-l, --language   Override the preferred language.

.SH FILES
.B ~/.metamorphose2/
.P
User-specific preference files are found here. Do not edit these files directly,
use the preferences menu.
.P
If there are problems with the application that persist after reinstalling it,
try deleting this folder.

.B ~/.metamorphose2/undo/
.P
Undo logs are stored here by default, this can be changed in preferences.

.B ~/.metamorphose2/configs/
.P
Configuration files are stored here by default.


.SH RESOURCES
Python 2.6, wxPython 2.8, Python Imaging Library (PIL), mutagen

.SH "SEE ALSO"
.BR python(1)

.SH COPYRIGHT
Métamorphose2 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Métamorphose2 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

.SH BUGS
Please check the bug reports at the project page:
.P
.B http://sourceforge.net/projects/file-folder-ren

.SH AUTHOR
Ianaré Sévi (ianare@gmail.com)
