Document: metamorphose2
Title: Debian metamorphose2 Manual
Author: <insert document author here>
Abstract: This manual describes what metamorphose2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/metamorphose2/metamorphose2.sgml.gz

Format: postscript
Files: /usr/share/doc/metamorphose2/metamorphose2.ps.gz

Format: text
Files: /usr/share/doc/metamorphose2/metamorphose2.text.gz

Format: HTML
Index: /usr/share/doc/metamorphose2/html/index.html
Files: /usr/share/doc/metamorphose2/html/*.html
